name: Django Tests

on:
  push:
    branches: [ main, hw1-p, hw1-f ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        echo "SECRET_KEY=django-insecure-test-key" > .env
        echo "DEBUG=True" >> .env
        
    - name: Run Tests
      run: |
        pytest myapp/tests.py -v
